version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - SQLX_OFFLINE=true
    container_name: mini_dex_core_app 
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mini_dex
      - SQLX_OFFLINE=true

  db:
    image: postgres:15
    container_name: mini_dex_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_dex
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: